const products = [
  {
    id: 1,
    name: 'Manual SGT-800',
    price: 100,
    image: 'img/sweden-1.jpg',
    version: 1,
    uploadedBy: 'Ida Elofsson',
    createdAt: '2018-01-01',
    createdBy: 'Robert Lönn',
    uploadedAt: '2018-09-01',
    storage: '739 kB',
    description: 'Beskrivande text',
    lock: true,
  },
  {
    id: 2,
    name: 'Manual SGT-750',
    price: 150,
    image: 'img/sweden-2.jpg',
    version: 2,
    uploadedBy: 'Ida Elofsson',
    createdAt: '2018-01-01',
    createdBy: 'Robert Lönn',
    uploadedAt: '2018-09-01',
    storage: '350 kB',
    description: 'Beskrivande text',
    lock: false,

  },
  {
    id: 3,
    name: 'Manual ångturbin, modell SST-900',
    price: 200,
    image: 'img/sweden-3.jpg',
    version: 4,
    uploadedBy: 'Ida Elofsson',
    createdAt: '2018-01-01',
    createdBy: 'Robert Lönn',
    uploadedAt: '2018-09-01',
    storage: '120 kB',
    description: 'Beskrivande text',
    lock: true,
  },
];

export default products;